// Copyright 2026 GenEye AI Labs Inc.
// Licensed under GPLv3. See LICENSE file.
//
// AgentInboxRegistry — process-wide registry of currently-running
// background automation scripts. Used by the side-panel chat to
// render a small "Running agents" tray so users can see what's
// happening in their delegated tasks.
//
// Threading: UI thread only. All callers (BackgroundRunHolder,
// chat handler IPC, side-panel poller) live on the UI thread, so
// no locking is needed.

#ifndef CHROME_BROWSER_MOLT_AI_AUTOMATION_AGENT_INBOX_REGISTRY_H_
#define CHROME_BROWSER_MOLT_AI_AUTOMATION_AGENT_INBOX_REGISTRY_H_

#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace base {
template <typename T>
class NoDestructor;
}  // namespace base

namespace molt_ai {
namespace automation {

struct AgentInboxEntry {
  AgentInboxEntry();
  AgentInboxEntry(const AgentInboxEntry&);
  AgentInboxEntry(AgentInboxEntry&&);
  AgentInboxEntry& operator=(const AgentInboxEntry&);
  AgentInboxEntry& operator=(AgentInboxEntry&&);
  ~AgentInboxEntry();

  int64_t id = 0;              // monotonic, generated by NewId()
  std::string script_id;       // matches Script.id
  std::string script_name;
  std::string start_url;       // first NAVIGATE step's URL
  int current_step = 0;        // 1-based, updated on every step
  int total_steps = 0;
  std::string status_note;     // "Click .submit", "Wait 5s", etc.
  int64_t started_at_unix = 0;
  bool succeeded = false;      // only meaningful when finished_at > 0
  int64_t finished_at_unix = 0;
};

class AgentInboxRegistry {
 public:
  static AgentInboxRegistry* Get();

  AgentInboxRegistry(const AgentInboxRegistry&) = delete;
  AgentInboxRegistry& operator=(const AgentInboxRegistry&) = delete;

  // Mint a new monotonic id for a new agent run.
  int64_t NewId();

  // Register a starting run. |entry.id| must be a fresh NewId().
  void Add(AgentInboxEntry entry);

  // Update progress for an in-flight run.
  void UpdateStep(int64_t id, int current_step, std::string note);

  // Mark a run finished. The entry stays in the registry briefly so
  // the UI can show the final status before it disappears.
  void Finish(int64_t id, bool succeeded);

  // Drop a finished entry (called after the UI has had a chance to
  // display it).
  void Remove(int64_t id);

  // Snapshot of all currently-tracked entries (running + just-
  // finished, oldest-first).
  std::vector<AgentInboxEntry> List() const;

 private:
  friend class base::NoDestructor<AgentInboxRegistry>;

  AgentInboxRegistry();
  ~AgentInboxRegistry();

  int64_t next_id_ = 1;
  std::map<int64_t, AgentInboxEntry> entries_;
};

}  // namespace automation
}  // namespace molt_ai

#endif  // CHROME_BROWSER_MOLT_AI_AUTOMATION_AGENT_INBOX_REGISTRY_H_
