// Copyright 2026 GenEye AI Labs Inc.
// Licensed under GPLv3. See LICENSE file.

#include "chrome/browser/molt_ai/tor/tor_manager.h"

#include <arpa/inet.h>
#include <netinet/in.h>
#include <signal.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>

#include <utility>

#include "build/build_config.h"

#include "base/command_line.h"
#include "base/files/file_path.h"
#include "base/files/file_util.h"
#include "base/functional/bind.h"
#include "base/logging.h"
#include "base/no_destructor.h"
#include "base/path_service.h"
#include "base/process/launch.h"
#include "base/strings/string_number_conversions.h"
#include "base/task/thread_pool.h"
#include "base/threading/platform_thread.h"
#include "base/time/time.h"
#include "chrome/browser/molt_ai/tor/tor_service.h"

namespace molt_ai {
namespace tor {

namespace {

// Common locations where tor lands across the popular installers.
// We probe in order and pick the first that's executable.
const char* const kCandidatePaths[] = {
    "/opt/homebrew/bin/tor",      // Apple Silicon Homebrew
    "/usr/local/bin/tor",          // Intel Homebrew, also Linux /usr/local
    "/usr/bin/tor",                // Debian/Ubuntu/Fedora package
    "/opt/local/bin/tor",          // MacPorts
};

// Where we keep our managed Tor data + torrc. Per user, under the
// MoltBrowser app-support directory. We pick a private dir so we
// don't clash with a system Tor's data dir (which holds the cookie
// file controlling auth — using a separate dir means each instance
// has its own).
base::FilePath ResolveAppSupportRoot() {
  base::FilePath home;
  if (!base::PathService::Get(base::DIR_HOME, &home))
    return base::FilePath();
#if BUILDFLAG(IS_MAC)
  return home.AppendASCII("Library")
      .AppendASCII("Application Support")
      .AppendASCII("MoltBrowser")
      .AppendASCII("tor");
#else
  return home.AppendASCII(".moltbrowser").AppendASCII("tor");
#endif
}

// Body run on a thread-pool task to wait for Tor to be reachable.
// Calls TorService::Get()->Probe() in a polling loop. Each probe
// already has a 300ms connect timeout, so we just loop until success
// or total_ms elapsed.
TorLaunchResult DoWaitForBootstrap(int total_ms) {
  TorLaunchResult r;
  const int kPollIntervalMs = 500;
  int waited = 0;
  while (waited < total_ms) {
    // TorService::Probe is async but we want sync here on the worker.
    // Easiest: just attempt a fresh control-port connection ourselves
    // (replicate the simple probe logic).
    // For simplicity we delegate to ProbeBlocking via a tiny helper:
    // we can't reach the anonymous-namespaced version directly, so we
    // do the same connect-attempt inline.
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd >= 0) {
      // Try connect with a small timeout.
      struct sockaddr_in addr {};
      addr.sin_family = AF_INET;
      addr.sin_port = htons(9051);
      addr.sin_addr.s_addr = htonl(0x7F000001);  // 127.0.0.1
      // Set send/recv timeouts.
      struct timeval tv;
      tv.tv_sec = 0;
      tv.tv_usec = 300000;
      setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
      setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));
      int rc = connect(fd, reinterpret_cast<struct sockaddr*>(&addr),
                       sizeof(addr));
      if (rc == 0) {
        close(fd);
        r.success = true;
        return r;
      }
      close(fd);
    }
    base::PlatformThread::Sleep(base::Milliseconds(kPollIntervalMs));
    waited += kPollIntervalMs;
  }
  r.success = false;
  r.error = "Tor did not become reachable within " +
            base::NumberToString(total_ms / 1000) + "s.";
  return r;
}

}  // namespace

// static
TorManager* TorManager::Get() {
  static base::NoDestructor<TorManager> instance;
  return instance.get();
}

TorManager::TorManager() = default;

TorManager::~TorManager() {
  // Best-effort cleanup. NoDestructor never actually runs this in
  // production, but useful for tests.
  Stop();
}

base::FilePath TorManager::GetDataDir() const {
  return ResolveAppSupportRoot();
}

base::FilePath TorManager::GetTorrcPath() const {
  return GetDataDir().AppendASCII("torrc");
}

bool TorManager::WriteTorrc() {
  base::FilePath dir = GetDataDir();
  if (dir.empty()) return false;
  if (!base::CreateDirectory(dir)) return false;
  // Write a minimal torrc that:
  //   - Binds SocksPort + ControlPort on loopback only
  //   - Uses cookie auth so anything besides MoltBrowser (running as
  //     the same user) can't connect
  //   - Keeps Tor's data dir under MoltBrowser/tor so we never touch
  //     a system Tor's state.
  std::string contents;
  contents += "# Auto-generated by MoltBrowser. Do not edit.\n";
  contents += "SocksPort 127.0.0.1:9050\n";
  contents += "ControlPort 127.0.0.1:9051\n";
  contents += "CookieAuthentication 1\n";
  contents += "DataDirectory " + dir.value() + "\n";
  contents += "Log notice file " + dir.AppendASCII("tor.log").value() + "\n";
  contents += "AvoidDiskWrites 1\n";
  return base::WriteFile(GetTorrcPath(), contents);
}

base::FilePath TorManager::ResolveTorBinary() const {
  for (const char* p : kCandidatePaths) {
    base::FilePath fp(p);
    if (base::PathExists(fp) &&
        access(fp.value().c_str(), X_OK) == 0) {
      return fp;
    }
  }
  return base::FilePath();
}

void TorManager::Launch(
    base::OnceCallback<void(TorLaunchResult)> on_ready) {
  // If we already have a healthy child, just confirm it.
  if (IsRunning()) {
    base::ThreadPool::PostTaskAndReplyWithResult(
        FROM_HERE,
        {base::MayBlock(), base::TaskPriority::USER_VISIBLE},
        base::BindOnce(&DoWaitForBootstrap, /*total_ms=*/2000),
        std::move(on_ready));
    return;
  }
  base::FilePath bin = ResolveTorBinary();
  if (bin.empty()) {
    TorLaunchResult r;
    r.error =
        "No tor binary found. Install with `brew install tor` (macOS) "
        "or `apt-get install tor` (Linux), then re-run /tor launch.";
    std::move(on_ready).Run(std::move(r));
    return;
  }
  if (!WriteTorrc()) {
    TorLaunchResult r;
    r.error = "Failed to write managed torrc to " + GetDataDir().value();
    std::move(on_ready).Run(std::move(r));
    return;
  }
  base::CommandLine cmd(bin);
  cmd.AppendArg("-f");
  cmd.AppendArgPath(GetTorrcPath());
  base::LaunchOptions opts;
  opts.new_process_group = true;
  base::Process p = base::LaunchProcess(cmd, opts);
  if (!p.IsValid()) {
    TorLaunchResult r;
    r.error = "Failed to spawn tor (LaunchProcess returned invalid).";
    r.binary_path = bin.value();
    std::move(on_ready).Run(std::move(r));
    return;
  }
  child_ = std::move(p);
  LOG(INFO) << "[MoltTor] launched " << bin.value()
            << " pid=" << child_.Pid();

  // Wait off-thread for the control port to come up.
  int pid_copy = child_.Pid();
  std::string bin_path_copy = bin.value();
  base::ThreadPool::PostTaskAndReplyWithResult(
      FROM_HERE,
      {base::MayBlock(), base::TaskPriority::USER_VISIBLE},
      base::BindOnce(&DoWaitForBootstrap, /*total_ms=*/45000),
      base::BindOnce(
          [](base::OnceCallback<void(TorLaunchResult)> cb,
             std::string bin_path, int pid,
             TorLaunchResult inner) {
            inner.binary_path = bin_path;
            inner.pid = pid;
            std::move(cb).Run(std::move(inner));
          },
          std::move(on_ready), bin_path_copy, pid_copy));
}

void TorManager::Stop() {
  if (!child_.IsValid()) return;
  // Polite first: SIGTERM. Tor handles it as a clean shutdown signal.
  pid_t pid = child_.Pid();
  ::kill(pid, SIGTERM);
  // Don't block the UI thread waiting; the OS will reap. We also
  // detach from our base::Process handle to avoid double-kill.
  child_ = base::Process();
  LOG(INFO) << "[MoltTor] sent SIGTERM to pid=" << pid;
}

}  // namespace tor
}  // namespace molt_ai
