#!/bin/bash
# MoltBrowser Build Configuration Script
# Copyright 2025 GenEye AI Labs Inc.
#
# Configures the Chromium build with MoltBrowser-specific settings.
# Uses GN (Generate Ninja) build system.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CHROMIUM_SRC="$ROOT_DIR/chromium/src"

export PATH="$ROOT_DIR/depot_tools:$PATH"

echo "=== MoltBrowser Build Configuration ==="

# Detect platform
PLATFORM="$(uname -s)"
ARCH="$(uname -m)"

echo "Platform: $PLATFORM"
echo "Architecture: $ARCH"

# Determine build output directory
BUILD_DIR="out/MoltBrowser"

cd "$CHROMIUM_SRC"

# GN build arguments for MoltBrowser
# Based on V4 spec: de-Googled, privacy-first, AI-native
GN_ARGS=$(cat <<'EOF'
# MoltBrowser Build Configuration
# Generated by configure.sh

# Build type
is_official_build = true
is_debug = false

# De-Google: Remove Google API dependencies
google_api_key = ""
google_default_client_id = ""
google_default_client_secret = ""

# Disable Google-specific features
safe_browsing_mode = 0
enable_reporting = false
enable_supervised_users = false
enable_google_now = false

# Branding
is_chrome_branded = false

# Performance
is_component_build = false
symbol_level = 0
enable_nacl = false

# Chrome extension compatibility (CRITICAL: must remain true)
enable_extensions = true

# Target architecture
EOF
)

# Add platform-specific args
if [ "$PLATFORM" = "Darwin" ]; then
  if [ "$ARCH" = "arm64" ]; then
    GN_ARGS+='
target_cpu = "arm64"
# Metal GPU acceleration for Apple Silicon
use_system_xcode = true
'
  else
    GN_ARGS+='
target_cpu = "x64"
use_system_xcode = true
'
  fi
elif [ "$PLATFORM" = "Linux" ]; then
  GN_ARGS+='
target_cpu = "x64"
# Vulkan for GPU acceleration
use_ozone = true
'
fi

echo ""
echo "GN Arguments:"
echo "$GN_ARGS"
echo ""

# Generate build files
echo "Generating build files in $BUILD_DIR..."
gn gen "$BUILD_DIR" --args="$GN_ARGS"

echo ""
echo "=== Configuration Complete ==="
echo ""
echo "Build directory: $CHROMIUM_SRC/$BUILD_DIR"
echo ""
echo "To build MoltBrowser:"
echo "  ./scripts/build.sh"
echo ""
